services:
  reservations:
    build:
      context: .
      dockerfile: apps/reservations/Dockerfile
      target: development
    command: pnpm start:dev reservations
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo

  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
      target: development
    command: pnpm start:dev auth
    ports:
      - '3001:3001'
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - '27017:27017'

