FROM public.ecr.aws/docker/library/node:alpine AS development

WORKDIR /usr/src/app

COPY package.json ./
COPY pnpm-lock.yaml ./
COPY pnpm-workspace.yaml ./
COPY .npmrc ./
COPY tsconfig.json tsconfig.json
COPY nest-cli.json nest-cli.json

RUN npm install -g pnpm@10

COPY /apps/payments apps/payments 

COPY libs libs

RUN pnpm install -r

RUN pnpm run build payments

FROM public.ecr.aws/docker/library/node:alpine AS production

ARG NODE_ENV=production

ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package.json ./
COPY pnpm-lock.yaml ./

RUN npm install -g pnpm@10

RUN pnpm install --prod

COPY --from=development /usr/src/app/dist ./dist

CMD ["node","dist/apps/payments/main"]
